blog/urls.py
from django.urls import path 
from . import views

urlpatterns = [
    path('', views.blog, name = 'blogs'),
    path('<int:id>/', views.blog_detail, name = 'blog_detail'),
]

marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('accounts/', include('accounts.urls')),
    # path('messages/', include('message.urls')),
    path('cart/', include('carts.urls')),

    #orders
    path('orders/', include('orders.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from accounts.models import Account
from store.models import Product, Variation


class Payment(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    payment_id = models.CharField(max_length=100)
    payment_method = models.CharField(max_length=100)
    amount_paid = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.payment_id


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled'),
    )

    user = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    order_number = models.CharField(max_length=20)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    email = models.EmailField(max_length=50)
    address_line_1 = models.CharField(max_length=50)
    address_line_2 = models.CharField(max_length=50, blank=True)
    country = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    order_note = models.CharField(max_length=100, blank=True)
    order_total = models.FloatField()
    tax = models.FloatField()
    discount = models.CharField(blank=True, null=True, max_length=20)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    # Extra methods for Order model
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def full_address(self):
        return f'{self.first_name} {self.address_line_1} {self.address_line_2}'

    def __str__(self):
        return self.first_name


# OrderProduct model
class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    quantity = models.IntegerField()
    product_price = models.FloatField()
    ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.product_name

templates/user/change_password.html
{% extends 'master/base.html' %} 
{% load static %} 
{% block content %}
 
<section class="section-conten padding-y bg">
  <div class="container">
    <div class="row">
      <aside class="col-md-3">
        <!--   SIDEBAR   -->
        <ul class="list-group">
         <a class="list-group-item" href="/dashboard/"> Dashboard </a>
          <a class="list-group-item" href="/my-orders/"> My Orders </a>
          <a class="list-group-item" href="/edit-profile/">
            Edit Profile
          </a>
           <a class="list-group-item" href="/change-password/">
            My Selling Items
          </a>
           <a class="list-group-item" href="/change-password/">
            Received Orders
          </a>
          <a class="list-group-item active" href="/change-password/">
            Change Password
          </a>
        </ul>
        <br />
        <a class="btn btn-light btn-block" href="/accounts/logout/">
          <i class="fa fa-power-off"></i> <span class="text">Log out</span>
        </a>
        <!--   SIDEBAR .//END   -->
      </aside>

      <main class="col-md-9">
        <article class="card">
          <header class="card-header">
            <strong class="d-inline-block mr-3">Change Your Password</strong>
          </header>
          <div class="card-body">
            <div class="row">
              <div class="col-md-12">
                <form action="/accounts/change_password/" method="POST">
                  <input
                    type="hidden"
                    name="csrfmiddlewaretoken"
                    value="IozPTAn6OBnzhZuDVangNiCLFsW1Dn5WdFs0zZS7hfCKtDS761tisfnLNlYISdHu"
                  />

                  <div class="form-group">
                    <label>Current Password</label>
                    <input
                      type="password"
                      name="current_password"
                      placeholder="Current Password"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label>Create new password</label>
                    <input
                      type="password"
                      name="new_password"
                      placeholder="Create New Password"
                      class="form-control"
                      required
                    />
                  </div>
                  <div class="form-group">
                    <label>Confirm new password</label>
                    <input
                      type="password"
                      name="confirm_password"
                      placeholder="Confirm New Password"
                      class="form-control"
                      required
                    />
                  </div>

                  <input type="submit" value="Submit" class="btn btn-primary" />
                </form>
              </div>
            </div>
            <!-- row.// -->
          </div>
          <!-- card-body .// -->
        </article>
        <!-- order-group.// -->
      </main>
    </div>
    <!-- row.// -->
  </div>
</section>
 
{% endblock %}

templates/user/dashboard.html
{% extends 'master/base.html' %} 
{% load static %} 
{% block content %}
  
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">
  <div class="container">
    <div class="row">
      <aside class="col-md-3">
        <!--   SIDEBAR   -->
        <ul class="list-group">
          <a class="list-group-item active" href="/dashboard/">
            Dashboard
          </a>
          <a class="list-group-item" href="/my-orders/"> My Orders </a>
          <a class="list-group-item" href="/edit-profile/">
            Edit Profile
          </a>
          <a class="list-group-item" href="#"> My Selling Items </a>
          <a class="list-group-item" href="#"> Received Orders </a>
          <a class="list-group-item" href="/change-password/">
            Change Password
          </a>
        </ul>
        <br />
        <a class="btn btn-light btn-block" href="/accounts/logout/">
          <i class="fa fa-power-off"></i> <span class="text">Log out</span>
        </a>
        <!--   SIDEBAR .//END   -->
      </aside>

      <main class="col-md-9">
        <article class="card">
          <header class="card-header">
            <strong class="d-inline-block mr-3">Logged in as:</strong>
            <span>Mohit Paudel</span>
          </header>
          <div class="card-body">
            <div class="row">
              <div class="col-md-6">
                <div class="card" style="text-align: center">
                  <div class="card-body">
                    <h5 class="card-title">Total Orders</h5>
                    <h4>5</h4>
                    <a href="/my-orders/">View Orders</a>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="card" style="text-align: center">
                  <div class="card-body">
                    <h5 class="card-title">Received Orders</h5>
                    <h4>10</h4>
                    <a href="/my-orders/">View Orders</a>
                  </div>
                </div>
              </div>
              
            </div>
            <!-- row.// -->
          </div>
          <!-- card-body .// -->
        </article>
        <!-- order-group.// -->
      </main>
    </div>
    <!-- row.// -->
  </div>
</section>

<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/user/edit_profile.html
{% extends 'master/base.html' %} 
{% load static %} 
{% block content %}
    
<section class="section-conten padding-y bg">
  <div class="container">
    <div class="row">
      <aside class="col-md-3">
        <!--   SIDEBAR   -->
        <ul class="list-group">
          <a class="list-group-item" href="/dashboard/">
            Dashboard
          </a>
          <a class="list-group-item" href="/my-orders/"> My Orders </a>
          <a class="list-group-item active" href="/edit-profile/">
            Edit Profile
          </a>
          <a class="list-group-item" href="#"> My Selling Items </a>
          <a class="list-group-item" href="#"> Received Orders </a>
          <a class="list-group-item" href="/change-password/">
            Change Password
          </a>
        </ul>
        <br />
        <a class="btn btn-light btn-block" href="/accounts/logout/">
          <i class="fa fa-power-off"></i> <span class="text">Log out</span>
        </a>
        <!--   SIDEBAR .//END   -->
      </aside>

      <main class="col-md-9">
        <article class="card">
          <header class="card-header">
            <strong class="d-inline-block mr-3">Edit your profile</strong>
          </header>
          <div class="card-body">
            <div class="text-right">
              <img
                src="/static/images/default/default-user.png"
                alt="Profile Picture"
                width="100"
                style="border-radius: 50px"
              />
            </div>
            <div class="row">
              <div class="col-md-12">
                <form
                  action="/accounts/edit_profile/"
                  method="POST"
                  enctype="multipart/form-data"
                >
                  <input
                    type="hidden"
                    name="csrfmiddlewaretoken"
                    value="SIHCbcMTGsQFp8ZZSEubAkmcjh3hIlRenZANRBhU965QBMnt3vAdfh7cra5YXbtM"
                  />
                  <div class="form-row">
                    <div class="form-group col-md-6">
                      <label>First Name</label>
                      <input
                        type="text"
                        name="first_name"
                        value="Islington"
                        maxlength="50"
                        class="form-control"
                        required
                        id="id_first_name"
                      />
                    </div>
                    <div class="form-group col-md-6">
                      <label>Last Name</label>
                      <input
                        type="text"
                        name="last_name"
                        value="College"
                        maxlength="50"
                        class="form-control"
                        required
                        id="id_last_name"
                      />
                    </div>
                  </div>
                  <div class="form-row">
                    <div class="form-group col-md-6">
                      <label>Phone Number</label>
                      <input
                        type="text"
                        name="phone_number"
                        value="9812344567"
                        maxlength="50"
                        class="form-control"
                        required
                        id="id_phone_number"
                      />
                    </div>
                    <div class="form-group col-md-6">
                      <label>Profile Picture</label>
                      <input
                        type="file"
                        name="profile_picture"
                        accept="image/*"
                        class="form-control"
                        id="id_profile_picture"
                      />
                    </div>
                  </div>
                  <div class="form-group">
                    <label>Address Line 1</label>
                    <input
                      type="text"
                      name="address_line_1"
                      maxlength="100"
                      class="form-control"
                      id="id_address_line_1"
                    />
                  </div>
                  <div class="form-group">
                    <label>Address Line 2</label>
                    <input
                      type="text"
                      name="address_line_2"
                      maxlength="100"
                      class="form-control"
                      id="id_address_line_2"
                    />
                  </div>
                  <div class="form-row">
                    <div class="form-group col-md-4">
                      <label>City</label>
                      <input
                        type="text"
                        name="city"
                        maxlength="20"
                        class="form-control"
                        id="id_city"
                      />
                    </div>
                    <div class="form-group col-md-4">
                      <label>State</label>
                      <input
                        type="text"
                        name="state"
                        maxlength="20"
                        class="form-control"
                        id="id_state"
                      />
                    </div>
                    <div class="form-group col-md-4">
                      <label>Country</label>
                      <input
                        type="text"
                        name="country"
                        maxlength="20"
                        class="form-control"
                        id="id_country"
                      />
                    </div>
                  </div>
                  <input type="submit" value="Save" class="btn btn-primary" />
                </form>
              </div>
            </div>
            <!-- row.// -->
          </div>
          <!-- card-body .// -->
        </article>
        <!-- order-group.// -->
      </main>
    </div>
    <!-- row.// -->
  </div>
</section>
 {% endblock %}

templates/user/login.html
{% extends 'master/base.html' %} 
{% load static %} 
{% block content %}
    
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

<!-- ============================ COMPONENT LOGIN   ================================= -->
	<div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
      <div class="card-body">
      <h4 class="card-title mb-4">Sign in</h4>
      <form>
          <div class="form-group">
			 <input type="email" class="form-control" placeholder="Email Address" >
          </div> <!-- form-group// -->
          <div class="form-group">
			<input type="password" class="form-control" placeholder="Password" >
          </div> <!-- form-group// -->
          
          <div class="form-group">
          	<a href="#" class="float-right">Forgot password?</a> 
           
          </div> <!-- form-group form-check .// -->
          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block"> Login  </button>
          </div> <!-- form-group// -->    
      </form>
      </div> <!-- card-body.// -->
    </div> <!-- card .// -->

     <p class="text-center mt-4">Don't have account? <a href="/register/">Sign up</a></p>
     <br><br>
<!-- ============================ COMPONENT LOGIN  END.// ================================= -->

</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/user/register.html
{% extends 'master/base.html' %} 
{% load static %} 
{% block content %}
  
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">

<!-- ============================ COMPONENT REGISTER   ================================= -->
	<div class="card mx-auto" style="max-width:520px; margin-top:40px;">
      <article class="card-body">
		<header class="mb-4"><h4 class="card-title">Sign up</h4></header>
		<form>
				<div class="form-row">
					<div class="col form-group">
						<label>First name</label>
					  	<input type="text" class="form-control" placeholder="">
					</div> <!-- form-group end.// -->
					<div class="col form-group">
						<label>Last name</label>
					  	<input type="text" class="form-control" placeholder="">
					</div> <!-- form-group end.// -->
				</div> <!-- form-row end.// -->
				<div class="form-group">
					<label>Email</label>
					<input type="email" class="form-control" placeholder="">
					<small class="form-text text-muted">We'll never share your email with anyone else.</small>
				</div> <!-- form-group end.// -->
				<div class="form-group">
					<label class="custom-control custom-radio custom-control-inline">
					  <input class="custom-control-input" checked="" type="radio" name="gender" value="option1">
					  <span class="custom-control-label"> Male </span>
					</label>
					<label class="custom-control custom-radio custom-control-inline">
					  <input class="custom-control-input" type="radio" name="gender" value="option2">
					  <span class="custom-control-label"> Female </span>
					</label>
				</div> <!-- form-group end.// -->
				<div class="form-row">
					<div class="form-group col-md-6">
					  <label>City</label>
					  <input type="text" class="form-control">
					</div> <!-- form-group end.// -->
					<div class="form-group col-md-6">
					  <label>Country</label>
					  <select id="inputState" class="form-control">
					    <option> Choose...</option>
					      <option>Uzbekistan</option>
					      <option>Russia</option>
					      <option selected="">United States</option>
					      <option>India</option>
					      <option>Afganistan</option>
					  </select>
					</div> <!-- form-group end.// -->
				</div> <!-- form-row.// -->
				<div class="form-row">
					<div class="form-group col-md-6">
						<label>Create password</label>
					    <input class="form-control" type="password">
					</div> <!-- form-group end.// --> 
					<div class="form-group col-md-6">
						<label>Repeat password</label>
					    <input class="form-control" type="password">
					</div> <!-- form-group end.// -->  
				</div>
			    <div class="form-group">
			        <button type="submit" class="btn btn-primary btn-block"> Register  </button>
			    </div> <!-- form-group// -->      
			        
			</form>
		</article><!-- card-body.// -->
    </div> <!-- card .// -->
    <p class="text-center mt-4">Have an account? <a href="/login/">Log In</a></p>
    <br><br>
<!-- ============================ COMPONENT REGISTER  END.// ================================= -->


</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
 
{% endblock %}